[package]
name = "mmd-wasm-runtime"
version = "0.32.0"
edition = "2021"
description = "Optimized WASM runtime for babylon.js MMD"
repository = "https://github.com/noname0310/babylon-mmd"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["wee_alloc", "console_error_panic_hook"]

[profile.release]
opt-level = 3

[dependencies]
nalgebra = "0.32.3"
wasm-bindgen = "0.2.88"
wee_alloc = { version = "0.4.5", optional = true }
console_error_panic_hook = { version = "0.1.7", optional = true }

[dependencies.web-sys]
version = "0.3.65"
features = ["console"]

[dev-dependencies]
wasm-bindgen-test = "0.3.38"
