[package]
name = "mmd-wasm-runtime"
version = "0.36.0"
edition = "2021"
description = "Optimized WASM runtime for babylon.js MMD"
repository = "https://github.com/noname0310/babylon-mmd"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook", "parallel"]
parallel = ["rayon", "wasm-bindgen-rayon"]

[profile.release]
opt-level = 3

[profile.dev]
opt-level = 3

[dependencies]
wasm-bindgen = "0.2.91"
console_error_panic_hook = { version = "0.1.7", optional = true }
byte-slice-cast = "1.2.2"
num-traits = "0.2.18"
glam = { version = "0.27.0", features = ["debug-glam-assert", "fast-math"] }
rayon = { version = "1.8.1", optional = true }
wasm-bindgen-rayon = { version = "1.2.1", optional = true }

[dependencies.web-sys]
version = "0.3.68"
features = ["console"]

[dev-dependencies]
wasm-bindgen-test = "0.3.41"
